create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('general', 'registration', 'correction', 'report', 'advertising')),
  name text not null,
  email text not null,
  subject text not null,
  related_url text,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

comment on table public.inquiries is '고객지원 통합 문의';
comment on column public.inquiries.type is 'general, registration, correction, report, advertising';

create index if not exists inquiries_type_created_at_idx
  on public.inquiries (type, created_at desc);

create index if not exists inquiries_status_created_at_idx
  on public.inquiries (status, created_at desc);
