-- EventZoa contact inquiries
-- Run this entire file in the Supabase SQL Editor.

begin;

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  email text not null,
  subject text not null,
  related_url text,
  message text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Preserve inquiries created with earlier contact categories.
alter table public.inquiries
  drop constraint if exists inquiries_type_check;

update public.inquiries
set type = case type
  when 'event' then 'registration'
  when 'support' then 'general'
  when 'partnership' then 'general'
  when 'advertising' then 'general'
  else type
end
where type in ('event', 'support', 'partnership', 'advertising');

alter table public.inquiries
  add constraint inquiries_type_check
  check (type in ('general', 'registration', 'correction', 'report'))
  not valid;

alter table public.inquiries
  validate constraint inquiries_type_check;

alter table public.inquiries
  drop constraint if exists inquiries_status_check;

alter table public.inquiries
  add constraint inquiries_status_check
  check (status in ('pending', 'in_progress', 'resolved', 'closed'))
  not valid;

alter table public.inquiries
  validate constraint inquiries_status_check;

create index if not exists inquiries_type_created_at_idx
  on public.inquiries (type, created_at desc);

create index if not exists inquiries_status_created_at_idx
  on public.inquiries (status, created_at desc);

create or replace function public.set_inquiries_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists inquiries_set_updated_at on public.inquiries;
create trigger inquiries_set_updated_at
before update on public.inquiries
for each row
execute function public.set_inquiries_updated_at();

alter table public.inquiries enable row level security;

revoke all on table public.inquiries from anon, authenticated;
revoke all on function public.set_inquiries_updated_at()
  from public, anon, authenticated;

grant all on table public.inquiries to service_role;
grant usage, select on sequence public.inquiries_id_seq to service_role;

comment on table public.inquiries is
  'Customer support inquiries submitted through EventZoa.';
comment on column public.inquiries.type is
  'general, registration, correction, report';
comment on column public.inquiries.status is
  'pending, in_progress, resolved, closed';

commit;
